CREATE TABLE IF NOT EXISTS EchoClips (
  ClipID      INTEGER PRIMARY KEY AUTOINCREMENT,
  Filename    TEXT    NOT NULL,
  Timestamp   TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  ContextTag  TEXT    NOT NULL
);